[tool.poetry]
name = "gulliver"
version = "0.1.0"
description = ""
authors = ["H. Turgut Uyar <uyar@tekir.org>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 96

[tool.tox]
legacy_tox_ini = """
[tox]
skipsdist = True
envlist = py{37,36}

[testenv]
deps =
    pytest
commands =
    {posargs:pytest}
"""
