[tool.poetry]
name = "gulliver"
version = "0.1.0"
description = ""
authors = ["H. Turgut Uyar <uyar@tekir.org>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
flake8 = "^3.6"

[tool.black]
line-length = 96

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py{37,36}, style
skipsdist = True

[testenv]
deps =
    pytest
commands =
    {posargs:pytest}

[testenv:style]
deps =
    flake8
commands =
    flake8 gulliver
"""
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

