# THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT MANUALLY.

from typing import Mapping

import pyramid.router

def create_app(
    global_config: Mapping, **settings
) -> pyramid.router.Router: ...
