# THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT MANUALLY.

from newt.db import BTree

import persistent.mapping

class Root(BTree): ...
def get_app_root(db_root: persistent.mapping.PersistentMapping) -> Root: ...
