# THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT MANUALLY.

from persistent.mapping import PersistentMapping

import pyramid.request

__version__ = ...  # type: str

class Root(PersistentMapping):
    def __init__(self) -> None: ...

def get_root(request: pyramid.request.Request) -> Root: ...
